# build 라는 이름의 이미지 생성
FROM maven:3.6 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package

FROM openjdk:11-jre-slim
WORKDIR /app

# build 라는 이름의 이미지를 실행한 컨테이너로부터 /app/target/*.jar 를 복사해옴
COPY --from=build /app/target/*.jar ./app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
