# maven 3.6 버전과 jdk-11 버전이 함께 설치되어있는 base iamge
FROM maven:3.6-jdk-11
WORKDIR /app

COPY pom.xml .
COPY src ./src

# mvn package 로 생성된 jar 파일은 /app/target 하위에 위치
RUN mvn clean package

RUN cp /app/target/*.jar ./app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
